# Generated by Django 3.1.2 on 2021-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasolina',
            fields=[
                ('idgasolina', models.CharField(db_column='IDGASOLINA', max_length=5, primary_key=True, serialize=False)),
                ('tipogasolina', models.CharField(db_column='TIPOGASOLINA', max_length=15)),
            ],
            options={
                'db_table': 'gasolina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('idperiodo', models.AutoField(db_column='IDPERIODO', primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(db_column='FECHAINICIO')),
                ('fechafin', models.DateField(db_column='FECHAFIN')),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('idzona', models.CharField(db_column='IDZONA', max_length=5, primary_key=True, serialize=False)),
                ('nombrezona', models.CharField(db_column='NOMBREZONA', max_length=15)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
    ]
