# Generated by Django 3.1.2 on 2021-06-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionarTablasSecundarias', '0002_auto_20210621_1731'),
        ('GestionarTablasSecundarias', '0002_auto_20210621_2329'),
    ]

    operations = [
    ]
