# Generated by Django 3.1.2 on 2021-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dui', models.CharField(db_column='DUI', max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='NOMBRES', max_length=40)),
                ('apellidos', models.CharField(db_column='APELLIDOS', max_length=40)),
                ('departamento', models.CharField(db_column='DEPARTAMENTO', max_length=20)),
                ('municipio', models.CharField(db_column='MUNICIPIO', max_length=20)),
                ('fecha_nacimiento', models.DateField(db_column='FECHA_NACIMIENTO')),
                ('correo', models.CharField(db_column='CORREO', max_length=40)),
                ('contrasena', models.CharField(db_column='CONTRASENA', max_length=16)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
