# Generated by Django 3.1.2 on 2021-06-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuario', '0002_auto_20210621_2329'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
