# Generated by Django 3.1.2 on 2021-06-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuario', '0003_auto_20210621_2358'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='USUARIO',
        ),
    ]
