# Generated by Django 3.1.2 on 2021-06-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prediccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prediccion',
            table='PREDICCION',
        ),
    ]
